### ISSUE TITLE
h$releaseAll missing

### ISSUE THREAD

**Issue by mtolly** [ghcjs/shims#14]
When I run `GHCJS.Foreign.releaseAll` from `ghcjs-base`:
```
uncaught exception in Haskell main thread: ReferenceError: Can't find variable: h$releaseAll
```
I assume it's supposed to be defined somewhere around https://github.com/ghcjs/shims/blob/5e11d33cb74f8522efca0ace8365c0dc994b10f6/src/mem.js#L1104-1128

**Comment by luite** [comment]
Cleaning up old tickets. Thanks for the report. I think this has been fixed, and in `improved-base` (now `master`) the library has changed so much that it's probably not relevant anyway.
