### ISSUE TITLE
Importing a Happy-generated parser causes crash due to a `fixme`

### ISSUE THREAD

**Issue by mtolly** [ghcjs/shims#17]
I get a JS exception when I run a program that includes a Happy-generated parser, even if I don't call the parse function. Here's a short Parse.y to test:

```haskell
{
module Parse (parse) where
}

%name parse
%tokentype { Bool }
%error { parseError }
%token
  t { True }
  f { False }

%%

int :: { Integer }
    : { 0 }
    | int t { 2 * $1 + 1 }
    | int f { 2 * $1 }

{
parseError :: [Bool] -> a
parseError _ = error "Parse error"
}
```

And Main.hs:

```haskell
module Main where

import Parse

main :: IO ()
main = print "ok!"
```

When I run this in Node I get:

```
/Users/mtolly/git/jshappy/dist/build/jshappy/jshappy.jsexe/all.js:5431
            throw "string arg";
```

which appears to be from https://github.com/ghcjs/shims/blob/6ada4bf1a084d1b80b993303d35ed863d219b031/src/mem.js#L254

I just installed a fresh GHCJS and I'm using the current Happy (1.19.5).

Here's the full Parse.hs generated by Happy: http://pastebin.com/ezVrjyNU

**Comment by mtolly** [comment]
I have worked around this for now by running Happy manually with none of the fancy extensions (Cabal runs it with `-agc` by default), so this is not super urgent for me.

**Comment by luite** [comment]
Thanks for providing a test case. Some patterns, like string literals in arguments are quite rare in code generated from normal Haskell. I hadn't implemented this yet since I didn't have a good test case for them.

I'll add an implementation in the coming days, during NZHac if I have time there.

**Comment by luite** [comment]
fixed in `improved-base`, which is getting closer to being merged

**Comment by luite** [comment]
Closing, it's been merged for a while now.
