### ISSUE TITLE
Error: h$runSyncAction: h$reschedule expected

### ISSUE THREAD

**Issue by ariep** [ghcjs/shims#32]
Websocket communication by ghcjs-generated code sometimes fails in the browser (firefox), giving:
`Error: h$runSyncAction: h$reschedule expected`.

Any idea what is wrong here? This happens consistently for a given communication pattern, while other instances of websocket communication work fine.

This is with latest ghcjs from github.

The same error apparently surfaced before for someone else: see [here](http://ircbrowse.net/browse/ghcjs?id=119217&timestamp=1446653294#t1446653294). Maybe the fix applied then did not fix my particular case?

**Comment by luite** [comment]
It's something in the scheduler seeing an inconsistent state. I added the check to catch more of these errors, but it may be too strict.

Do you have some code that I could use to reproduce this problem?

**Comment by ariep** [comment]
Right now, the code is scattered over many unpublished repositories, but I'll see if I can package it up. Do you want just the javascript output, or the generating haskell code? And do you need the server part as well, to see the websocket communication in action?

**Comment by luite** [comment]
Ideally I'd have a way to rebuild everything, a docker or vagrant image, or nix, would work. But by the looks of it, this issue may actually be not too difficult to track down without the client side haskell source. I'd still need some way to make it actually hit the bug. Perhaps you can try to replace the server response with some JS code that returns the expected result after some delay?

**Comment by ariep** [comment]
Luite, I've contactly you personally by email to see if we can set you up with my development machine to get at this bug.

**Comment by ariep** [comment]
For now, I have rewritten my application to reduce the size of websocket payloads. This seems to circumvent the problem, for now anyway.
I'll reopen if this pops up again.
