### ISSUE TITLE
`h$processConstants` is divided in subobjects, but used as if it conains constants directly

### ISSUE THREAD

**Issue by zaquest** [ghcjs/shims#38]
On node v6.3.0 `process['binding']('constants')` returns object that contains subobjects that in turn contain actual constants. But in code it is used as if it directly contained these constants. For example here https://github.com/ghcjs/shims/blob/master/pkg/base.js#L152.
It makes impossible opening files with any flags, which leads for example to build errors in build scripts that use `openBinaryTempFileWithDefaultPermissions`.

**Comment by luite** [comment]
Fixed in the `ghc-8.0` and `master` branches, thanks for the report.
